### PR TITLE
Add test for Breaking change MovedStagingProperties

### PR DESCRIPTION
**Pull request by Seiphon**
Hi @jtydhr88 
For other test, I can't find the real code for test, I searched from portal 7.1, 7.0, even ee-6.2, but still can't find them.

### CODE REVIEW

**Comment by jtydhr88** [comment]
SF Successfully on liferay-ide folder

**Comment by Seiphon** [comment]
The test file has been updated.

**Comment by jtydhr88** [comment]
SF Successfully on liferay-ide folder

**Comment by jtydhr88** [comment]
sent to Greg, thanks.

**Pull request closed without merging**
