### PR TITLE
IDE-4189 Redeploy action doesn't work

### PR DESCRIPTION
**Pull request by Seiphon**
Hi @jtydhr88 

For this issue, the reason is the parameter selectedServer always be null, so I give it a value when executing the selectinChanged() method.

Br,
Seiphon

### CODE REVIEW

**Comment by yanan** [comment]
sf retest

**Comment by yanan** [comment]
sf retest

**Comment by jtydhr88** [comment]
SF Successfully on liferay-ide folder

**Comment by jtydhr88** [comment]
sent to Greg, thanks.

**Pull request closed without merging**
